version: "3.8"

services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    networks:
      - app_network
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - 9200:9200
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - app_network
  webapi:
    build: .
    ports:
      - "5000:5000"
    networks:
      - app_network
volumes:
  esdata:
    driver: local
networks:
  app_network:
    driver: bridge